# model backbone

backbone:
  [[-1, 1, ConvLayer, [64, 6, 2, 2]],  # 0-P1/2
   [-1, 1, ConvLayer, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3Layer  , [128]],
   [-1, 1, ConvLayer, [256, 3, 2]],  # 3-P3/8
   [-1, 6, C3Layer  , [256]],
   [-1, 1, ConvLayer, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3Layer  , [512]],
   [-1, 1, ConvLayer, [1024, 3, 2]],  # 7-P5/32
   [-1, 3, C3Layer  , [1024]],
   [-1, 1, SPPF     , [1024, 5]],  # 9
  ]